# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Remove live-session packages from the installed system.
---
backend: apt

skip_if_no_internet: false
update_db: false
update_system: false

operations:
    -   type: "remove"
        packages:
            - live-boot
            - live-boot-initramfs-tools
            - live-config
            - live-config-systemd
            - live-tools
            - calamares
