# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Unpack the Debian root filesystem shipped on the live ISO medium.
---
unpack:
    -   source: /run/live/medium/live/filesystem.squashfs
        sourcefs: squashfs
        destination: ""
