# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Debian user defaults for esterOS installs.
---
defaultGroups:
    - name: users
      must_exist: true
      system: true
    - lp
    - video
    - network
    - storage
    - audio
    - name: sudo
      must_exist: false
      system: true

sudoersGroup: sudo

autologinGroup: autologin

doAutologin: false

setRootPassword: false

doReusePassword: false

passwordRequirements:
    minLength: 1
    maxLength: -1

userShell: /bin/bash

writeHostsFile: true

overwriteExistingHostname: false

homewelcome: false

reuseHome: false

removeExistingUsers: false
