# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# esterOS Calamares settings for the Debian live installer ISO.
---
modules-search: [ local ]

sequence:
- show:
  - welcomeq
  - localeq
  - keyboardq
  - partition
  - usersq
  - summaryq
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - locale
  - keyboard
  - localecfg
  - fstab
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - initramfs
  - bootloader
  - umount
- show:
  - finishedq

branding: esteros

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
