# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Unpack the example Generic distro image built by the example-distro target.
# Paths are relative to $BUILDDIR when calamares is started from there.
---
unpack:
    -   source: ./example.sqfs
        sourcefs: squashfs
        destination: ""
