# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Unpack the example distro built by `ninja example-distro`.
# Path is relative to the build directory (where calamares is started).
---
unpack:
    -   source: ./example.sqfs
        sourcefs: squashfs
        destination: ""
