# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Relaxed requirements for loopback-disk install testing.
---
qmlSearch: both

showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    1.0
    requiredRam:        0.5
    check:
        - storage
        - ram
    required:
        - storage
        - ram

geoip:
    style:    "none"
